"""Change module names

Revision ID: 11698c2657b0
Revises: 7b7bf15fcc24
Create Date: 2022-04-20 23:22:42.257072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11698c2657b0'
down_revision = '7b7bf15fcc24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sku', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=1023), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='product_pkey'),
    sa.UniqueConstraint('sku', name='product_sku_key')
    )
    # ### end Alembic commands ###
